version: '3.8'

services:
  debezium-connect:
    image: debezium/connect:2.5
    container_name: cdc-debezium
    environment:
      BOOTSTRAP_SERVERS: localhost:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium.config
      OFFSET_STORAGE_TOPIC: debezium.offsets
      STATUS_STORAGE_TOPIC: debezium.status

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_REST_ADVERTISED_PORT: 8083

    ports:
      - "8083:8083"
    restart: unless-stopped
